pipeline {
    agent any

    options { buildDiscarder(logRotator(numToKeepStr: '7', 
                            daysToKeepStr: '10')) 
    }

    parameters { 
        string(name: 'VERSION', defaultValue: 'SNAPSHOT', description: 'La version de la aplicacion') 
    }

    stages {
        stage('ExLimpiar WorkSpace') {
                       
            steps {
                cleanWs()
            }
        }
        stage('Maven Verify') {
                       
            steps {
                echo "mvn verify"
                echo "*************************************************************"
                println "mvn verify"
            }
        }

        stage('Maven Test') {
                       
            steps {
                echo "mvn test"
            }
        }

        stage('Maven Install') {
                       
            steps {
                echo "mvn install"
            }
        }

        stage('Create file') {
                       
            steps {
                sh 'touch file1.txt'
            }
        }
        stage('Create custon file') {
                       
            steps {
                sh 'touch file1-"$VERSION".txt'
            }
        }

        
    }
    post { 
        always { 
            echo 'I will always say Hello again!'
            chuckNorris()
        }
        success { 
            echo 'I will say Hello again only if success!'
        }
        failure { 
            echo 'I will say Hello again only if failure!'
        }
        aborted { 
            script {
                echo 'I will say Hello again only if aborted!'
            }
        }
    }
}