pipeline {
    agent any
    
    options {
        buildDiscarder(logRotator(numToKeepStr: '7', 
                                  daysToKeepStr: '10'))
    }
    
    parameters {
        string(name: 'VERSION', defaultValue: 'SNAPSHOT', description: 'La version de la aplicacion que queremos desplegar')
        string(name: 'ORIGIN_FILE', description: 'ruta absoluta del fichero origen', defaultValue: '/home/jenkins')
        string(name: 'DESTINATION_FILE', description: 'ruta absoluta del fichero origen')
    }
    
    stages {
        stage ('Clean WorkSpace'){
            steps {
                cleanWs()
            }
        }
    stage ('Maven Test'){
        steps {
            println "mvn verify"
        }
    }
    
    stage ('Maven Install'){
        steps {
            echo "mvn install"
        }
    }
    stage ('Create file'){
        steps {
            sh 'touch file1.txt'
        }
    }
    stage ('Maven verify'){
        steps {
            echo "mvn verify"
        }
    }
    stage ('Create custom file'){
        steps {
            sh 'touch file1-$VERSION.txt'
        }
    }
    }
    
    post {
        always {
            chuckNorris()
        }
        
    }
}