pipeline {
    agent any

    options {
        buildDiscarder(logRotator(numToKeepStr: '7',
                                  daysToKeepStr: '10'))
        timestamps()
    }

    parameters{
        string(name: 'ORIGIN_FILE', defaultValue: '/Users/dmerinov/Desktop/colaborativoJenkins/knowmadmood-jenkins-marzo-2024/david_merino_vecino/Jenkinsfile',
        description: 'ruta de origen del fichero')

        string(name: 'DESTINATION_FILE', defaultValue: '/Users/dmerinov/Desktop/colaborativoJenkins/knowmadmood-jenkins-marzo-2024/dmerinov-zip-file/Jenkinsfile.7z',
        description: 'ruta de destino del fichero')
        
        string(name: 'CPU_CORES', defaultValue: '2',
        description: 'num cores que se usan en la tarea')
    
        choice(name: 'COMPRESS_TYPE', choices: ['Fastest','Fast','Normal','Maximum','Ultra'],
        description: 'tipo de compresion')}

    stages {
        stage('Clean WorkSpace') {
            steps {
                cleanWs()
            }
        }
    }
}

/*
7z a -r -mmt2 /Users/dmerinov/Desktop/colaborativoJenkins/knowmadmood-jenkins-marzo-2024/dmerinov-zip-file/Jenkinsfile.7z /Users/dmerinov/Desktop/colaborativoJenkins/knowmadmood-jenkins-marzo-2024/david_merino_vecino/Jenkinsfile -mx9
*/