pipeline{
    agent {label 'minion2'}

    options {
        buildDiscarder(logRotator(numToKeepStr: '7',
                                  daysToKeepStr: '10'))
        timestamps()                           
    }

    parameters {
        string(name: 'ORIGIN_FILE', defaultValue: '/home/jenkins/myfile',description:'el nombre del fichero de origen a comprimir')
        string(name: 'DESTINATION_FILE', defaultValue:'/home/jenkins/myfile.7z',description:'el nombre del archivo que tiene que tener mi archivo comprimido')
        string(name: 'CPU_CORES', defaultValues:'2',description:'Numero de cores con los que se realiza la compresion')
        choices(name: 'COMPRSS_TYPE', choices:['FASTEST','NORMAL','MAXIMUM','ULTRA'],description:'Selecciona el nivel de compresion que vamos a utilizar')
    }

    stages{
        stage ('Limpiar Workspace'){
            steps {
                cleanWs()
            }
        }

    }
    post {
        always {
            chuckNorris()
        }
    }
}
