pipeline {
    agent { 
        label 'minion2'
    }
     options { 
        buildDiscarder(logRotator(numToKeepStr: '7', daysToKeepStr: '10'))
        timestamps()
    }

    parameters {
        string (name: 'SOURCE_PATH', description: 'Ruta del archivo a comprimir', trim: true, defaultValue: '/home/jenkins/projects/development-pipeline/maikelalonsobana-zip-file/myFile')
        string (name: 'TARGET_PATH', description: 'Ruta de destino del archivo comprimido', trim: true, defaultValue: '/home/jenkins/projects/development-pipeline/maikelalonsobana-zip-file/myFile.7z')
        string (name: 'NUMBER_OF_CORES', description: 'Número de núcleos a utilizar para comprimir', trim: true, defaultValue: '2')
        choice (name: 'COMPRESSION_LEVEL', description: 'Selecciona el nivel de compresión deseado', choices: ['Fastest','Fast','Normal','Maximum','Ultra'], defaultValue: 'Ultra')
    }

    stages {
        stage('Clean workspace') {
            steps {
                println "Deleting workspace..."
                cleanWs()
            }
        }
    }

    // 
    post {
        always {
            // se ejecuta siempre en esta fase de post
            chuckNorris()
        }
    }
}
/* 7za a -r -mmt2 /home/jenkins/projects/development-pipeline/maikelalonsobana-zip-file/Jenkinsfile.7z /home/jenkins/projects/development-pipeline/maikelalonsobana-zip-file/Jenkinsfile -mx9 */