pipeline {
    agent any

    options { buildDiscarder(logRotator(numToKeepStr: '7', 
                            daysToKeepStr: '10')) 
    }

    parameters { 
        string(name: 'ORIGIN_FILE', defaultValue: '/home/jenkins', description: 'Donde se encuentra el fichero de origen a comprimir') 
    }

    stages {
        stage('Limpiar WorkSpace') {
                       
            steps {
                cleanWs()
            }
        }
        
        
    }
    post { 
        always { 
            echo 'I will always say Hello again!'
            chuckNorris()
        }
        success { 
            echo 'I will say Hello again only if success!'
        }
        failure { 
            echo 'I will say Hello again only if failure!'
        }
        aborted { 
            script {
                echo 'I will say Hello again only if aborted!'
            }
        }
    }
}